import React, { useState, useEffect } from 'react';
import {
  Sparkles,
  ShieldCheck,
  Users,
  Calendar,
  Briefcase,
  Bot,
  ArrowRight,
  ChevronDown,
  Lock,
  Layers,
  BarChart3,
  CheckCircle2,
  UserPlus as UserPlusIcon
} from 'lucide-react';

interface LandingPageProps {
  onOpenAuth: (mode: 'signin' | 'signup') => void;
  onExploreDemo: () => void;
}

export const LandingPage: React.FC<LandingPageProps> = ({ onOpenAuth, onExploreDemo }) => {
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const [stats, setStats] = useState({
    studentCount: 1,
    facultyCount: 1,
    totalUsers: 2
  });

  // Fetch real-time dynamic stats from Express backend API
  useEffect(() => {
    const fetchRealtimeStats = async () => {
      try {
        const res = await fetch('http://localhost:5000/api/stats');
        const data = await res.json();
        if (data.success) {
          setStats({
            studentCount: data.studentCount || 0,
            facultyCount: data.facultyCount || 0,
            totalUsers: data.totalUsers || 0
          });
        }
      } catch (err) {
        // Fallback
      }
    };
    fetchRealtimeStats();
  }, []);

  const faqs = [
    {
      q: 'How does the Real-Time Email OTP Verification work?',
      a: 'When registering, a real 6-digit OTP verification code is generated by our Node.js backend server and delivered straight to your email inbox via Nodemailer SMTP.'
    },
    {
      q: 'What roles are supported in AetherCampus?',
      a: 'AetherCampus supports 4 distinct role portals: Student, Faculty, Coordinator, and Administrator. Each role unlocks tailored features, permissions, and dashboards based on user registration.'
    },
    {
      q: 'Are the student and faculty counts updated in real time?',
      a: 'Yes! Whenever a new student or faculty registers and verifies their email OTP, the real-time statistics counter automatically updates live across the platform.'
    },
    {
      q: 'How does the Aether AI Campus Copilot assist users?',
      a: 'The AI Copilot performs instant attendance risk audits, assignment rubric outlines, placement resume keyword analysis, and voice-synthesized campus responses.'
    }
  ];

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 font-sans selection:bg-sky-500 selection:text-white">
      
      {/* LANDING NAVIGATION HEADER */}
      <header className="sticky top-0 z-40 bg-white/95 backdrop-blur-md border-b border-slate-200 shadow-xs">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-20 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-2xl bg-gradient-to-tr from-sky-500 to-sky-600 text-white shadow-lg shadow-sky-500/30">
              <Sparkles className="w-6 h-6" />
            </div>
            <div>
              <span className="text-2xl font-extrabold tracking-tight text-slate-900 font-display">
                Aether<span className="text-sky-600">Campus</span>
              </span>
              <span className="ml-2 px-2.5 py-0.5 text-[11px] uppercase font-extrabold tracking-wider bg-sky-100 text-sky-700 border border-sky-300 rounded-full">
                Real-Time AI
              </span>
            </div>
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={() => onOpenAuth('signin')}
              aria-label="Sign In"
              className="px-5 py-2.5 text-xs font-extrabold text-slate-700 hover:text-sky-600 hover:bg-slate-100 rounded-xl transition-all"
            >
              Sign In
            </button>

            <button
              onClick={() => onOpenAuth('signup')}
              aria-label="Register Now"
              className="px-5 py-2.5 bg-sky-600 hover:bg-sky-500 text-white text-xs font-extrabold rounded-xl shadow-lg shadow-sky-500/25 hover:shadow-sky-500/40 transition-all flex items-center gap-2"
            >
              <span>Register Now</span>
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      </header>

      {/* HERO SECTION WITH TOPIC IMAGE */}
      <section className="relative pt-12 pb-20 overflow-hidden bg-gradient-to-b from-sky-50/70 via-white to-slate-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          
          <div className="text-center max-w-4xl mx-auto">
            <div className="inline-flex items-center gap-2 px-4 py-2 bg-sky-100/90 border border-sky-300 rounded-full text-sky-800 text-xs font-extrabold mb-6 animate-fade-in shadow-xs">
              <ShieldCheck className="w-4 h-4 text-sky-600" />
              <span>DevFusion 4.0 Hackathon • Smart Campus Management Platform</span>
            </div>

            <h1 className="text-4xl sm:text-6xl font-extrabold text-slate-900 tracking-tight leading-tight">
              The Next-Generation <span className="text-transparent bg-clip-text bg-gradient-to-r from-sky-600 via-sky-500 to-indigo-600">Smart Campus</span> Intelligence Hub
            </h1>

            <p className="mt-6 text-base sm:text-xl text-slate-600 max-w-2xl mx-auto leading-relaxed font-medium">
              Unifying Students, Faculty, Coordinators, and Administrators into one centralized platform powered by real-time Nodemailer OTP verification, live WhatsApp-style chat, and AI Copilot.
            </p>

            <div className="mt-8 flex flex-col sm:flex-row items-center justify-center gap-4">
              <button
                onClick={() => onOpenAuth('signup')}
                aria-label="Create Free Account"
                className="w-full sm:w-auto px-8 py-4 bg-sky-600 hover:bg-sky-500 text-white font-extrabold text-sm rounded-2xl shadow-xl shadow-sky-600/30 hover:shadow-sky-600/40 transition-all flex items-center justify-center gap-3 transform hover:-translate-y-0.5"
              >
                <UserPlusIcon className="w-5 h-5" />
                <span>Create Free Account</span>
              </button>

              <button
                onClick={() => {
                  const el = document.getElementById('roles-showcase');
                  if (el) el.scrollIntoView({ behavior: 'smooth' });
                  else onExploreDemo();
                }}
                aria-label="Explore Portals"
                className="w-full sm:w-auto px-8 py-4 bg-white hover:bg-slate-100 border border-slate-300 text-slate-800 font-extrabold text-sm rounded-2xl shadow-md transition-all flex items-center justify-center gap-3"
              >
                <Layers className="w-5 h-5 text-sky-600" />
                <span>Explore 4 Role Portals</span>
              </button>
            </div>
          </div>

          {/* HERO ORIGINAL IMAGE BANNER (/images/hero.jpg) */}
          <div className="mt-12 relative max-w-5xl mx-auto rounded-3xl overflow-hidden shadow-2xl border-4 border-white bg-slate-900 group">
            <img
              src="/images/hero.jpg"
              alt="Smart Campus Management Platform AI Dashboard"
              className="w-full h-auto object-cover transform group-hover:scale-102 transition-transform duration-700"
              onError={(e) => {
                e.currentTarget.src = 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1200&auto=format&fit=crop&q=80';
              }}
            />
            <div className="absolute inset-0 bg-gradient-to-t from-slate-950/80 via-transparent to-transparent flex items-end p-6 sm:p-8">
              <div className="bg-white/95 backdrop-blur-md p-4 sm:p-6 rounded-2xl border border-slate-200 shadow-xl max-w-xl text-left">
                <div className="flex items-center gap-2 text-sky-700 font-extrabold text-xs uppercase tracking-wider mb-1">
                  <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                  <span>Real-Time Unified Architecture</span>
                </div>
                <h3 className="text-lg sm:text-xl font-extrabold text-slate-900">
                  Full 4-Role Smart Campus Ecosystem
                </h3>
                <p className="text-xs text-slate-600 mt-1">
                  Live Attendance PIN/QR, GitHub Assignment Grading, Placement Drives, and Multi-Language Chat.
                </p>
              </div>
            </div>
          </div>

          {/* Hero Feature Pills */}
          <div className="mt-12 pt-8 border-t border-slate-200/80 grid grid-cols-2 md:grid-cols-4 gap-4 text-left max-w-5xl mx-auto">
            <div className="flex items-center gap-3 p-4 bg-white rounded-2xl border border-slate-200 shadow-xs hover:border-sky-400 transition-colors">
              <Lock className="w-5 h-5 text-sky-600 shrink-0" />
              <div>
                <strong className="block text-xs font-bold text-slate-900">Real Email OTP</strong>
                <span className="text-[11px] text-slate-500">Nodemailer SMTP</span>
              </div>
            </div>

            <div className="flex items-center gap-3 p-4 bg-white rounded-2xl border border-slate-200 shadow-xs hover:border-sky-400 transition-colors">
              <Bot className="w-5 h-5 text-sky-600 shrink-0" />
              <div>
                <strong className="block text-xs font-bold text-slate-900">AI Campus Copilot</strong>
                <span className="text-[11px] text-slate-500">Voice Synthesis</span>
              </div>
            </div>

            <div className="flex items-center gap-3 p-4 bg-white rounded-2xl border border-slate-200 shadow-xs hover:border-sky-400 transition-colors">
              <Users className="w-5 h-5 text-sky-600 shrink-0" />
              <div>
                <strong className="block text-xs font-bold text-slate-900">Real-Time Stats</strong>
                <span className="text-[11px] text-slate-500">Dynamic Counter</span>
              </div>
            </div>

            <div className="flex items-center gap-3 p-4 bg-white rounded-2xl border border-slate-200 shadow-xs hover:border-sky-400 transition-colors">
              <BarChart3 className="w-5 h-5 text-sky-600 shrink-0" />
              <div>
                <strong className="block text-xs font-bold text-slate-900">Live Analytics</strong>
                <span className="text-[11px] text-slate-500">Recharts Metrics</span>
              </div>
            </div>
          </div>

        </div>
      </section>

      {/* DYNAMIC REAL-TIME STATS SECTION */}
      <section className="py-12 bg-sky-600 text-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 grid grid-cols-2 md:grid-cols-4 gap-8 text-center">
          <div>
            <span className="text-4xl sm:text-5xl font-extrabold block font-mono">{stats.studentCount}</span>
            <span className="text-xs text-sky-100 uppercase tracking-wider font-extrabold">Registered Students (Live)</span>
          </div>
          <div>
            <span className="text-4xl sm:text-5xl font-extrabold block font-mono">{stats.facultyCount}</span>
            <span className="text-xs text-sky-100 uppercase tracking-wider font-extrabold">Faculty Members (Live)</span>
          </div>
          <div>
            <span className="text-4xl sm:text-5xl font-extrabold block font-mono">{stats.totalUsers}</span>
            <span className="text-xs text-sky-100 uppercase tracking-wider font-extrabold">Total System Users</span>
          </div>
          <div>
            <span className="text-4xl sm:text-5xl font-extrabold block font-mono">100%</span>
            <span className="text-xs text-sky-100 uppercase tracking-wider font-extrabold">SMTP OTP Verified</span>
          </div>
        </div>
      </section>

      {/* CORE MODULES & ORIGINAL IMAGES SHOWCASE GRID */}
      <section id="roles-showcase" className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <div className="inline-flex items-center gap-2 px-3 py-1 bg-sky-100 text-sky-800 border border-sky-300 rounded-full text-xs font-bold mb-3">
              <Layers className="w-4 h-4 text-sky-600" />
              <span>Interactive Role Portals</span>
            </div>
            <h2 className="text-3xl font-extrabold text-slate-900">Explore Unified Role-Based Campus Modules</h2>
            <p className="mt-2 text-sm text-slate-600">Select any role below to view its feature breakdown and access its dashboard</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            
            {/* Classroom Image Card (/images/classroom.jpg) */}
            <div className="rounded-3xl overflow-hidden border border-slate-200 shadow-xl bg-slate-900 group relative min-h-[300px]">
              <img
                src="/images/classroom.jpg"
                alt="Smart Classroom Management"
                className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700 opacity-80"
                onError={(e) => {
                  e.currentTarget.src = 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&auto=format&fit=crop&q=80';
                }}
              />
              <div className="absolute inset-0 bg-gradient-to-t from-slate-950/90 via-slate-950/40 to-transparent p-6 sm:p-8 flex flex-col justify-end text-left">
                <span className="px-3 py-1 bg-sky-500 text-white text-[10px] uppercase font-extrabold rounded-md w-fit mb-2">Smart Classroom</span>
                <h3 className="text-2xl font-extrabold text-white">Interactive Digital Academics</h3>
                <p className="text-xs text-slate-300 mt-1">Live PIN attendance, PDF study vaults, and instant submission grading.</p>
              </div>
            </div>

            {/* Events Image Card (/images/events.jpg) */}
            <div className="rounded-3xl overflow-hidden border border-slate-200 shadow-xl bg-slate-900 group relative min-h-[300px]">
              <img
                src="/images/events.jpg"
                alt="Campus Events & Hackathons"
                className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700 opacity-80"
                onError={(e) => {
                  e.currentTarget.src = 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&auto=format&fit=crop&q=80';
                }}
              />
              <div className="absolute inset-0 bg-gradient-to-t from-slate-950/90 via-slate-950/40 to-transparent p-6 sm:p-8 flex flex-col justify-end text-left">
                <span className="px-3 py-1 bg-indigo-500 text-white text-[10px] uppercase font-extrabold rounded-md w-fit mb-2">Events & Clubs</span>
                <h3 className="text-2xl font-extrabold text-white">Campus Events & QR Gate Pass</h3>
                <p className="text-xs text-slate-300 mt-1">Coordinator event studio, club registrations, and QR ticket validation.</p>
              </div>
            </div>

          </div>
        </div>
      </section>

      {/* FAQ ACCORDION */}
      <section className="py-20 px-4 sm:px-6 lg:px-8 max-w-4xl mx-auto text-left">
        <div className="text-center mb-12">
          <h2 className="text-3xl font-extrabold text-slate-900">Frequently Asked Questions</h2>
          <p className="text-sm text-slate-600 mt-1">Everything you need to know about the AetherCampus platform architecture</p>
        </div>

        <div className="space-y-4">
          {faqs.map((faq, idx) => (
            <div
              key={idx}
              className="bg-white border border-slate-200 rounded-2xl overflow-hidden shadow-xs transition-all"
            >
              <button
                onClick={() => setOpenFaq(openFaq === idx ? null : idx)}
                className="w-full p-5 text-left flex items-center justify-between font-extrabold text-sm text-slate-900"
              >
                <span>{faq.q}</span>
                <ChevronDown className={`w-5 h-5 text-sky-600 transition-transform ${openFaq === idx ? 'rotate-180' : ''}`} />
              </button>

              {openFaq === idx && (
                <div className="p-5 pt-0 text-xs text-slate-600 leading-relaxed border-t border-slate-100 font-medium">
                  {faq.a}
                </div>
              )}
            </div>
          ))}
        </div>
      </section>

      {/* FOOTER */}
      <footer className="py-12 border-t border-slate-200 bg-slate-900 text-slate-400 text-xs">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col sm:flex-row items-center justify-between gap-6">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-xl bg-sky-600 text-white">
              <Sparkles className="w-4 h-4" />
            </div>
            <span className="font-extrabold text-white text-base">AetherCampus</span>
            <span className="text-slate-400">© 2026 DevFusion 4.0 Hackathon. All rights reserved.</span>
          </div>

          <div className="flex items-center gap-6 font-bold">
            <button onClick={() => onOpenAuth('signin')} className="hover:text-white">Sign In</button>
            <button onClick={() => onOpenAuth('signup')} className="hover:text-white">Register</button>
            <a href="http://localhost:5000/api/health" target="_blank" rel="noreferrer" className="text-emerald-400 hover:underline">
              ● API Status
            </a>
          </div>
        </div>
      </footer>

    </div>
  );
};
